-- 코드를 작성해주세요
SELECT A.ID,
CASE
    WHEN A.PER <= 0.25 THEN 'CRITICAL'
    WHEN A.PER > 0.25 AND PER <= 0.5 THEN 'HIGH'
    WHEN A.PER > 0.5 AND PER <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM 
(SELECT *,
 PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
 FROM ECOLI_DATA) AS A
ORDER BY ID ASC